# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/dequerol/Documents/1. Areas/InstalledPrograms/C++/00_FlowSimulator"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/dequerol/Documents/1. Areas/InstalledPrograms/C++/00_FlowSimulator/build"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/dequerol/Documents/1. Areas/InstalledPrograms/C++/00_FlowSimulator/build/CMakeFiles" "/Users/dequerol/Documents/1. Areas/InstalledPrograms/C++/00_FlowSimulator/build//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/dequerol/Documents/1. Areas/InstalledPrograms/C++/00_FlowSimulator/build/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FlowSimulator

# Build rule for target.
FlowSimulator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FlowSimulator
.PHONY : FlowSimulator

# fast build rule for target.
FlowSimulator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlowSimulator.dir/build.make CMakeFiles/FlowSimulator.dir/build
.PHONY : FlowSimulator/fast

src/flow.o: src/flow.cpp.o
.PHONY : src/flow.o

# target to build an object file
src/flow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlowSimulator.dir/build.make CMakeFiles/FlowSimulator.dir/src/flow.cpp.o
.PHONY : src/flow.cpp.o

src/flow.i: src/flow.cpp.i
.PHONY : src/flow.i

# target to preprocess a source file
src/flow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlowSimulator.dir/build.make CMakeFiles/FlowSimulator.dir/src/flow.cpp.i
.PHONY : src/flow.cpp.i

src/flow.s: src/flow.cpp.s
.PHONY : src/flow.s

# target to generate assembly for a file
src/flow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlowSimulator.dir/build.make CMakeFiles/FlowSimulator.dir/src/flow.cpp.s
.PHONY : src/flow.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlowSimulator.dir/build.make CMakeFiles/FlowSimulator.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlowSimulator.dir/build.make CMakeFiles/FlowSimulator.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlowSimulator.dir/build.make CMakeFiles/FlowSimulator.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/pipe.o: src/pipe.cpp.o
.PHONY : src/pipe.o

# target to build an object file
src/pipe.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlowSimulator.dir/build.make CMakeFiles/FlowSimulator.dir/src/pipe.cpp.o
.PHONY : src/pipe.cpp.o

src/pipe.i: src/pipe.cpp.i
.PHONY : src/pipe.i

# target to preprocess a source file
src/pipe.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlowSimulator.dir/build.make CMakeFiles/FlowSimulator.dir/src/pipe.cpp.i
.PHONY : src/pipe.cpp.i

src/pipe.s: src/pipe.cpp.s
.PHONY : src/pipe.s

# target to generate assembly for a file
src/pipe.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlowSimulator.dir/build.make CMakeFiles/FlowSimulator.dir/src/pipe.cpp.s
.PHONY : src/pipe.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... FlowSimulator"
	@echo "... src/flow.o"
	@echo "... src/flow.i"
	@echo "... src/flow.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/pipe.o"
	@echo "... src/pipe.i"
	@echo "... src/pipe.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

